version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./debug.Dockerfile
    stdin_open: true
    tty: true 
    volumes:
      - node_modules:/home/node/node_modules # required because node_modules is not in bodhitree-web github repository
      - .:/home/node
    ports:
      - 7654:7654

volumes: 
  node_modules: